### PR TITLE
WIP: Set elasticsearch config for breaking changes in ES 8.0

### PR DESCRIPTION
**Pull request by michaelborn**
It seems ES 8.0 changed the way they generated a default password. They now autogenerate a default password unless `ELASTIC_PASSWORD` is specified, and expect the user to run `bin/elasticsearch-reset-password -u elastic` to manually reset the password.

In addition, it seems connections use `https` by default.

As you can see, all cbElasticsearch builds have been failing since the update to use 8.0.0 in the test suite.

See https://www.elastic.co/guide/en/elasticsearch/reference/current/release-notes-8.0.0.html

### CODE REVIEW

**Comment by michaelborn** [comment]
I can't get CFML to hit Elasticsearch over the configured connection. :facepalm: No idea what's wrong there.

**Comment by jclausen** [comment]
There are a bunch of breaking changes in v8 of Elasticsearch.  We are going to need to create a separate branch and somehow maintain backward compatibility

**Comment by jclausen** [comment]
I have reverted the build to use ES 7.x - which is now succeeding for all engines.  There are some different JVM args which were causing the container to exit.  We will need to add a separate matrix for ES8 because updating will require backward compatibility be maintained to 7.x while adding support for 8.  As we do this 6.x compatibility can be dropped completely ( e.g. the conditional logic dealing with index `type` values.

**Comment by michaelborn** [comment]
Oh, that's just great. I missed that fact - was more confused by the connection failure... if that's what the JSON error was after all. 🤔

-------- Original Message --------

**Comment by jclausen** [comment]
The ES8 instance wouldn't start up because the JVM args are different, is all.

**Comment by michaelborn** [comment]
I'm going to close this PR, since it sounds like we're a long way from ES 8 compat and I don't want to clutter the field.

**Pull request closed without merging**
